import type { Entry, Production } from "./catering";

/** Rows copied from گزارش گردش مواد اولیه و تولید مهر ۱۴۰۵ (۱۴ تا ۱۶ مهر). */
export const SEED_ENTRIES: Entry[] = [
  {
    "id": "seed-e-1",
    "date": "1405/07/15",
    "mat": "سینه مرغ",
    "matCode": "M001",
    "qty": 49.0,
    "sup": "زربال",
    "inv": "F-1403-101",
    "note": "ورود صبح",
    "ts": 1
  },
  {
    "id": "seed-e-2",
    "date": "1405/07/15",
    "mat": "ران مرغ",
    "matCode": "M002",
    "qty": 200.0,
    "sup": "زربال",
    "inv": "F-1403-101",
    "note": "",
    "ts": 2
  },
  {
    "id": "seed-e-3",
    "date": "1405/07/15",
    "mat": "سینه فسنجان",
    "matCode": "M006",
    "qty": 10.0,
    "sup": "زربال",
    "inv": "F-1403-102",
    "note": "",
    "ts": 3
  },
  {
    "id": "seed-e-4",
    "date": "1405/07/15",
    "mat": "سینه سالاد",
    "matCode": "M007",
    "qty": 3.0,
    "sup": "زربال",
    "inv": "F-1403-103",
    "note": "",
    "ts": 4
  },
  {
    "id": "seed-e-5",
    "date": "1405/07/15",
    "mat": "گوشت نخودی",
    "matCode": "M003",
    "qty": 52.0,
    "sup": "شیخی",
    "inv": "",
    "note": "",
    "ts": 5
  },
  {
    "id": "seed-e-6",
    "date": "1405/07/16",
    "mat": "ماهی",
    "matCode": "M005",
    "qty": 10.0,
    "sup": "مقدم",
    "inv": "",
    "note": "",
    "ts": 6
  },
  {
    "id": "seed-e-7",
    "date": "1405/07/16",
    "mat": "گوشت خورشتی",
    "matCode": "M004",
    "qty": 30.0,
    "sup": "شیخی",
    "inv": "",
    "note": "",
    "ts": 7
  },
  {
    "id": "seed-e-8",
    "date": "1405/07/16",
    "mat": "سینه فسنجان",
    "matCode": "M006",
    "qty": 6.4,
    "sup": "مرادی",
    "inv": "",
    "note": "جهت غذای پرسنل داده شد جایگزین مرغ فسنجان گردید",
    "ts": 8
  }
];

export const SEED_PRODS: Production[] = [
  {
    "id": "seed-p-1",
    "date": "1405/07/14",
    "prod": "گوشت خورشت قورمه",
    "prodCode": "P010",
    "qty": 12.0,
    "session": "",
    "staff": "میثم خواجه",
    "staffCode": "S002",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 12.0,
    "material": "گوشت خورشتی",
    "materialCode": "M004",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 1
  },
  {
    "id": "seed-p-2",
    "date": "1405/07/15",
    "prod": "جوجه معمولی 170 گرمی",
    "prodCode": "P001",
    "qty": 50.0,
    "session": "s2",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "10:45",
    "end": "12:30",
    "duration": 105,
    "remain": 0,
    "note": "",
    "weightKg": 8.5,
    "material": "سینه مرغ",
    "materialCode": "M001",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 2
  },
  {
    "id": "seed-p-3",
    "date": "1405/07/15",
    "prod": "جوجه ممتاز ۲۰۰ گرمی",
    "prodCode": "P002",
    "qty": 50.0,
    "session": "s2",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "10:45",
    "end": "12:30",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 10.0,
    "material": "سینه مرغ",
    "materialCode": "M001",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 3
  },
  {
    "id": "seed-p-4",
    "date": "1405/07/15",
    "prod": "کوبیده اکو 100گرمی",
    "prodCode": "P004",
    "qty": 28.0,
    "session": "s1",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "08:00",
    "end": "10:30",
    "duration": 150,
    "remain": 0,
    "note": "",
    "weightKg": 2.1,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 4
  },
  {
    "id": "seed-p-5",
    "date": "1405/07/15",
    "prod": "لقمه معمولی 120گرمی",
    "prodCode": "P005",
    "qty": 35.0,
    "session": "s1",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "08:00",
    "end": "10:30",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 3.15,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 5
  },
  {
    "id": "seed-p-6",
    "date": "1405/07/15",
    "prod": "لقمه مجلسی 150گرمی",
    "prodCode": "P006",
    "qty": 22.0,
    "session": "s1",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "08:00",
    "end": "10:30",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 2.486,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 6
  },
  {
    "id": "seed-p-7",
    "date": "1405/07/15",
    "prod": "ران مرغ زرشک",
    "prodCode": "P007",
    "qty": 50.0,
    "session": "",
    "staff": "راجا کشمیری",
    "staffCode": "S001",
    "start": "08:30",
    "end": "11:00",
    "duration": 150,
    "remain": 0,
    "note": "",
    "weightKg": 50.0,
    "material": "ران مرغ",
    "materialCode": "M002",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 7
  },
  {
    "id": "seed-p-8",
    "date": "1405/07/15",
    "prod": "کوبیده اکو 100گرمی",
    "prodCode": "P004",
    "qty": 18.0,
    "session": "s3",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "17:00",
    "end": "18:15",
    "duration": 75,
    "remain": 0,
    "note": "",
    "weightKg": 1.35,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 8
  },
  {
    "id": "seed-p-9",
    "date": "1405/07/15",
    "prod": "لقمه مجلسی 150گرمی",
    "prodCode": "P006",
    "qty": 41.0,
    "session": "s3",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "17:00",
    "end": "18:15",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 4.633,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 9
  },
  {
    "id": "seed-p-10",
    "date": "1405/07/15",
    "prod": "لقمه معمولی 120گرمی",
    "prodCode": "P005",
    "qty": 14.0,
    "session": "s3",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "17:00",
    "end": "18:15",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 1.26,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 10
  },
  {
    "id": "seed-p-11",
    "date": "1405/07/15",
    "prod": "جوجه معمولی 170 گرمی",
    "prodCode": "P001",
    "qty": 27.0,
    "session": "e1",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "18:00",
    "end": "18:25",
    "duration": 25,
    "remain": 0,
    "note": "",
    "weightKg": 4.59,
    "material": "سینه مرغ",
    "materialCode": "M001",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 11
  },
  {
    "id": "seed-p-12",
    "date": "1405/07/15",
    "prod": "جوجه ممتاز ۲۰۰ گرمی",
    "prodCode": "P002",
    "qty": 1.0,
    "session": "e1",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "18:00",
    "end": "18:25",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 0.2,
    "material": "سینه مرغ",
    "materialCode": "M001",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 12
  },
  {
    "id": "seed-p-13",
    "date": "1405/07/15",
    "prod": "مرغ خورشت فسنجان",
    "prodCode": "P011",
    "qty": 6.0,
    "session": "",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 6.0,
    "material": "سینه فسنجان",
    "materialCode": "M006",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 13
  },
  {
    "id": "seed-p-14",
    "date": "1405/07/15",
    "prod": "گوشت خورشت قیمه",
    "prodCode": "P009",
    "qty": 4.0,
    "session": "",
    "staff": "مصطفی خوشگفتار",
    "staffCode": "S003",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 4.0,
    "material": "گوشت خورشتی",
    "materialCode": "M004",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 14
  },
  {
    "id": "seed-p-15",
    "date": "1405/07/15",
    "prod": "کوبیده اکو 100گرمی",
    "prodCode": "P004",
    "qty": 48.0,
    "session": "",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 3.6,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 15
  },
  {
    "id": "seed-p-16",
    "date": "1405/07/15",
    "prod": "لقمه معمولی 120گرمی",
    "prodCode": "P005",
    "qty": 28.0,
    "session": "",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 2.52,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 16
  },
  {
    "id": "seed-p-17",
    "date": "1405/07/15",
    "prod": "ماهی قزل",
    "prodCode": "P008",
    "qty": 5.0,
    "session": "",
    "staff": "راجا کشمیری",
    "staffCode": "S001",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 5.0,
    "material": "ماهی",
    "materialCode": "M005",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 17
  },
  {
    "id": "seed-p-18",
    "date": "1405/07/15",
    "prod": "لقمه مجلسی 150گرمی",
    "prodCode": "P006",
    "qty": 3.0,
    "session": "",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 0.339,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 18
  },
  {
    "id": "seed-p-19",
    "date": "1405/07/16",
    "prod": "ران مرغ زرشک",
    "prodCode": "P007",
    "qty": 40.0,
    "session": "",
    "staff": "راجا کشمیری",
    "staffCode": "S001",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 40.0,
    "material": "ران مرغ",
    "materialCode": "M002",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 19
  },
  {
    "id": "seed-p-20",
    "date": "1405/07/16",
    "prod": "کوبیده اکو 100گرمی",
    "prodCode": "P004",
    "qty": 33.0,
    "session": "s4",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "08:00",
    "end": "10:10",
    "duration": 130,
    "remain": 0,
    "note": "",
    "weightKg": 2.475,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 20
  },
  {
    "id": "seed-p-21",
    "date": "1405/07/16",
    "prod": "لقمه معمولی 120گرمی",
    "prodCode": "P005",
    "qty": 33.0,
    "session": "s4",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "08:00",
    "end": "10:10",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 2.97,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 21
  },
  {
    "id": "seed-p-22",
    "date": "1405/07/16",
    "prod": "لقمه مجلسی 150گرمی",
    "prodCode": "P006",
    "qty": 23.0,
    "session": "s4",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "08:00",
    "end": "10:10",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 2.599,
    "material": "گوشت نخودی",
    "materialCode": "M003",
    "remainKg": 0,
    "remainderType": "برگشت به مواد",
    "ts": 22
  },
  {
    "id": "seed-p-23",
    "date": "1405/07/16",
    "prod": "جوجه ممتاز ۲۰۰ گرمی",
    "prodCode": "P002",
    "qty": 40.0,
    "session": "",
    "staff": "صفرملک زاده",
    "staffCode": "S005",
    "start": "10:45",
    "end": "11:30",
    "duration": 45,
    "remain": 0,
    "note": "",
    "weightKg": 8.0,
    "material": "سینه مرغ",
    "materialCode": "M001",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 23
  },
  {
    "id": "seed-p-24",
    "date": "1405/07/16",
    "prod": "گوشت خورشت قیمه",
    "prodCode": "P009",
    "qty": 12.0,
    "session": "",
    "staff": "میثم خواجه",
    "staffCode": "S002",
    "start": "10:45",
    "end": "11:30",
    "duration": 45,
    "remain": 0,
    "note": "",
    "weightKg": 12.0,
    "material": "گوشت خورشتی",
    "materialCode": "M004",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 24
  },
  {
    "id": "seed-p-25",
    "date": "1405/07/16",
    "prod": "گوشت پخته خورشتی",
    "prodCode": "P013",
    "qty": 2.5,
    "session": "",
    "staff": "مصطفی خوشگفتار",
    "staffCode": "S003",
    "start": "11:45",
    "end": "12:30",
    "duration": 45,
    "remain": 0,
    "note": "",
    "weightKg": 2.5,
    "material": "گوشت خورشتی",
    "materialCode": "M004",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 25
  },
  {
    "id": "seed-p-26",
    "date": "1405/07/16",
    "prod": "جوجه معمولی 170 گرمی",
    "prodCode": "P001",
    "qty": 82.0,
    "session": "e2",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "13:00",
    "end": "14:30",
    "duration": 90,
    "remain": 0,
    "note": "",
    "weightKg": 13.94,
    "material": "سینه مرغ",
    "materialCode": "M001",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 26
  },
  {
    "id": "seed-p-27",
    "date": "1405/07/16",
    "prod": "جوجه ممتاز ۲۰۰ گرمی",
    "prodCode": "P002",
    "qty": 39.0,
    "session": "e2",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "13:00",
    "end": "14:30",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 7.8,
    "material": "سینه مرغ",
    "materialCode": "M001",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 27
  },
  {
    "id": "seed-p-28",
    "date": "1405/07/16",
    "prod": "مرغ سالاد ماکارونی",
    "prodCode": "P012",
    "qty": 1.0,
    "session": "",
    "staff": "مهدی عصمتی",
    "staffCode": "S004",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 1.5,
    "material": "سینه سالاد",
    "materialCode": "M007",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 28
  },
  {
    "id": "seed-p-29",
    "date": "1405/07/16",
    "prod": "ماهی قزل",
    "prodCode": "P008",
    "qty": 4.0,
    "session": "",
    "staff": "راجا کشمیری",
    "staffCode": "S001",
    "start": "",
    "end": "",
    "duration": null,
    "remain": 0,
    "note": "",
    "weightKg": 4.0,
    "material": "ماهی",
    "materialCode": "M005",
    "remainKg": 0,
    "remainderType": "حمل به روز بعد",
    "ts": 29
  }
];
